#configurations for encoder networks

root: '_encoders'

nets : {
    NET01 : {
        head  : ['4','M'],
        tail  : ['4'],    
    },

    NET02 : {
        head  : ['32', 'M', '64', 'M'],
        tail  : ['128'],    
    },

    NET03 : {
        head  : ['32', 'M', '64', 'M'],
        tail  : ['128', 'D#0.5'],    
    },

    NET04 : {
        head  : ['32#BN', 'M', '64#BN', 'M'],
        tail  : ['128'],    
    },

    NET05 : {
        head  : ['32#IN', 'M', '64#IN', 'M'],
        tail  : ['128'],    
    },
}


train : {
    epochs: 1,
    log_interval: 20,
    batch_size: 32,
    optimizer : { 
        optim : 'Adam',
        lr : 1e-4,        
    }
}

# 'VGG05': [64, 'M', 128, 'M'],
# 'VGG07': [64, 'M', 128, 'M', 256, 256, 'M'],
# 'VGG11': [64, 'M', 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M'],
# 'VGG13': [64, 64, 'M', 128, 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M'],
# 'VGG16': [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512, 'M'],
# 'VGG19': [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 256, 'M', 512, 512, 512, 512, 'M', 512, 512, 512, 512, 'M'],

