test_root   : 'epochs_draw_128'
dim         : 128
num_classes : 2

observed_set  : {
  root            : 'qd_shapes',
  imgs_per_class  : 25000,
  sources         : ['full_binary_circle.bin','full_binary_square.bin'],
  sources_url     : 'https://console.cloud.google.com/storage/quickdraw_dataset/full/binary/', 
  min_sz          : 30
}

coverage_set : {
  root : 'sd_shapes',
  imgs_per_class : 5000,  
  draw_limits    : {sz_lo : 30, sz_hi : 120, br_lo : 100, br_hi : 255, th  : 5}
}

encoders : {

    root : 'encoders',
    nets : {
        VGG07: {
            head : ['64', 'M', '128', 'M', '256', '256', 'M'],
            tail : ['2048', '1024']
        },
        VGG07BN: {
            head : ['64#BN', 'M', '128#BN', 'M', '256#BN', '256#BN', 'M'],
            tail : ['2048', '1024']
        },
        VGG11: {
            head : ['64', 'M', '128', 'M', '256', '256', 'M', '512', '512', 'M', '512', '512', 'M'],
            tail : ['2048', '1024']
        },
        VGG13: {
            head : ['64', '64', 'M', '128', '128', 'M', '256', '256', 'M', '512', '512', 'M', '512', '512', 'M'],              
            tail : ['2048', '1024']
        }
    },

    train : {
      epochs: 5,
      log_interval: 20,
      batch_size: 32,
      optimizer : { 
          optim : 'Adam',
          lr : 1e-4,        
      }
    }
}