test_root   : 'draw_28'
dim         : 28
num_classes : 2

observed_set  : {
  root            : 'qd_shapes',
  imgs_per_class  : 25000,
  sources         : ['full_binary_circle.bin','full_binary_square.bin'],
  sources_url     : 'https://console.cloud.google.com/storage/quickdraw_dataset/full/binary/',
  min_sz          : 4
}

coverage_set : {
  root : 'sd_shapes',
  imgs_per_class : 5000,
  draw_limits    : {sz_lo : 5, sz_hi : 10, br_lo : 100, br_hi : 255, th  : 1}
}

encoders : {

    root : 'encoders',
    nets : {
        NET01 : {
            head  : ['4','M'],
            tail  : ['4'],    
        },

        NET02 : {
            head  : ['32', 'M', '64', 'M'],
            tail  : ['128'],    
        },

        NET03 : {
            head  : ['32', 'M', '64', 'M'],
            tail  : ['128', 'D#0.5'],    
        },

        NET04 : {
            head  : ['32#BN', 'M', '64#BN', 'M'],
            tail  : ['128'],    
        },

        NET05 : {
            head  : ['32#IN', 'M', '64#IN', 'M'],
            tail  : ['128'],    
        },
    },

    train : {
        epochs: 1,
        log_interval: 20,
        batch_size: 32,
        optimizer : { 
            optim : 'Adam',
            lr : 1e-4,        
        }
    }

}